# This workflow is called from build workflows in other repos,
# such as cyberdojo/.github/workflows/main.yml.
# This has two consequences:
# 1) The checkout action in the find-snyk-vulns job must specify
#    its own repository explicitly (not rely on the default).
# 2) The workflow cannot rely on GitHub env-vars that are only
#    present at the repo level.

name: Artifact Snyk Test

on:
  workflow_call:
    outputs:
      trail_names:
        description: "JSON array of Kosli trail names attested to"
        value: ${{jobs.collect-trail-names.outputs.trail_names}}
    secrets:
      snyk_token:
        required: true
      kosli_api_token:
        required: true

    inputs:
      aws_rolename:
        description: "Rolename for permission to download artifact"
        required: false
        type: string
        default: "gh_actions_snyk_scanning"
      artifact_name:
        description: "Artifact name"
        required: true
        type: string
      artifact_fingerprint:
        description: "Artifact fingerprint/digest (64 chars)"
        required: true
        type: string
      repo_name:
        description: "Artifact repo"
        required: true
        type: string
      git_commit:
        description: "Artifact commit (40 chars)"
        required: true
        type: string
      raw_snyk_policy_url:
        description: "URL of snyk policy file (in commit for artifact)"
        required: true
        type: string
      kosli_flow:
        description: "Name of Kosli flow to attest snyk vulns to"
        required: true
        type: string


env:
  KOSLI_DEBUG:   ${{vars.KOSLI_DEBUG}}   # true/false
  KOSLI_DRY_RUN: ${{vars.KOSLI_DRY_RUN}} # true/false
  KOSLI_HOST:    ${{vars.KOSLI_HOST}}    # https://app.kosli.com
  KOSLI_ORG:     ${{vars.KOSLI_ORG}}     # cyber-dojo


jobs:
  create-snyk-cat:
    uses: ./.github/workflows/create-snyk-cat.yml
    secrets:
      kosli_api_token: ${{secrets.kosli_api_token}}


  find-snyk-vulns:
    runs-on: ubuntu-latest
    needs: [create-snyk-cat]
    outputs:
      vulns: ${{steps.set-vulns.outputs.vulns}}
      version: ${{steps.set-version.outputs.version}}
    permissions:
      id-token: write
      contents: write
    env:
      SNYK_SARIF_FILENAME: snyk.container.test.json
      SNYK_POLICY_FILENAME: .snyk
    steps:
      - uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@v6
        with:
          repository: cyber-dojo/snyk-scanning
          ref: main
          fetch-depth: 1

      - name: Load docker image from registry
        uses: cyber-dojo/load-image-from-registry@main
        with:
          image_name: ${{inputs.artifact_name}}
          aws_rolename: ${{inputs.aws_rolename}}

      - name: Setup Snyk
        uses: snyk/actions/setup@master
        with:
          snyk-version: v1.1300.2

      - name: Fail if the sarif file already exists
        run: |
          if test -f ${SNYK_SARIF_FILENAME} ; then
            echo "ERROR: ${SNYK_SARIF_FILENAME} already exists"
            exit 42
          fi

      - name: Set empty .snyk policy file
        run:
          echo > ${SNYK_POLICY_FILENAME}

      - name: Run Snyk container test
        env:
          SNYK_TOKEN: ${{secrets.snyk_token}}
        run:
          snyk container test ${{inputs.artifact_name}}
            --policy-path=${SNYK_POLICY_FILENAME}
            --sarif
            --sarif-file-output=${SNYK_SARIF_FILENAME} || true

      - name: Fail if the sarif file is not created
        run: |
          if ! test -f ${SNYK_SARIF_FILENAME} ; then
            echo "ERROR: ${SNYK_SARIF_FILENAME} was not created"
            exit 43
          fi

      - name: Get the real .snyk file
        run: |
          curl --fail-with-body "${{inputs.raw_snyk_policy_url}}" > ${SNYK_POLICY_FILENAME}
          cat ${SNYK_POLICY_FILENAME}

      - name: Combine vulns in sarif file with snyk policy file
        id: set-vulns
        env:
          JSON_FILENAME: vulns.json
        run: |
          ./bin/combine_snyk.py ${SNYK_SARIF_FILENAME} ${SNYK_POLICY_FILENAME} > ${JSON_FILENAME}                  
          vulns="$(jq --compact-output . ${JSON_FILENAME})"
          # jq . <<< "${vulns}"
          echo "vulns=${vulns}" >> ${GITHUB_OUTPUT}

      - name: Output snyk version
        id: set-version
        run:
          echo "version=$(snyk --version)" >> ${GITHUB_OUTPUT}


  attest-snyk-vulns:
    needs: [create-snyk-cat, find-snyk-vulns]
    if: ${{needs.find-snyk-vulns.outputs.vulns != '[]'}}
    runs-on: ubuntu-latest
    env:
      ATTESTATION_DATA_FILENAME: custom.json
      KOSLI_API_TOKEN: ${{secrets.kosli_api_token}}
      KOSLI_FLOW: ${{inputs.kosli_flow}}
    strategy:
      matrix:
        include: ${{fromJSON(needs.find-snyk-vulns.outputs.vulns)}}
    steps:
      - uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup Kosli CLI
        uses: kosli-dev/setup-cli-action@v3
        with:
          version: ${{vars.KOSLI_CLI_VERSION}}

      - name: Set Kosli trail name
        run:
          echo "KOSLI_TRAIL=${{inputs.repo_name}}-${{matrix.snyk_severity}}-${{matrix.snyk_full_id}}" >> "${GITHUB_ENV}"

      - name: Get time vuln first seen for this repo 
        run: |
          kosli begin trail ${KOSLI_TRAIL} # idempotent
          kosli get trail ${KOSLI_TRAIL} --output json > trail.json
          echo "FIRST_SEEN_TS=$(jq '.created_at' trail.json)" >> ${GITHUB_ENV}

      - name: Create file containing snyk vuln data
        run:
          jq
            --arg     version              "${{needs.find-snyk-vulns.outputs.version}}"
            --arg     id                   "${{matrix.snyk_full_id}}"
            --arg     severity             "${{matrix.snyk_severity}}"
            --arg     url                  "${{matrix.snyk_vuln_url}}"
            --argjson ignore_expires_exists ${{matrix.snyk_ignore_expires_exists}}
            --arg     ignore_expires       "${{matrix.snyk_ignore_expires}}"
            --argjson ignore_expires_ts     ${{matrix.snyk_ignore_expires_ts}}
            --argjson first_seen_ts         ${FIRST_SEEN_TS}
            '$ARGS.named' <<< '{}' 
            > ${ATTESTATION_DATA_FILENAME}

      - name: Print custom attestation data
        if: ${{env.KOSLI_DEBUG == 'true'}}
        run:
          cat ${ATTESTATION_DATA_FILENAME}

      - name: Attest artifact to Kosli
        run:
          kosli attest artifact ${{inputs.artifact_name}}
            --fingerprint ${{inputs.artifact_fingerprint}}
            --name artifact

      - name: Attest snyk vuln to Kosli
        run:
          kosli attest custom ${{inputs.artifact_name}}
            --annotate snyk_URL=${{matrix.snyk_vuln_url}}
            --attestation-data ${ATTESTATION_DATA_FILENAME}
            --fingerprint ${{inputs.artifact_fingerprint}}
            --name artifact.snyk
            --type ${{needs.create-snyk-cat.outputs.name}}


  collect-trail-names:
    needs: [find-snyk-vulns, attest-snyk-vulns]
    if: always() && needs.find-snyk-vulns.result == 'success'
    runs-on: ubuntu-latest
    outputs:
      trail_names: ${{steps.set-trail-names.outputs.trail_names}}
    env:
      VULNS: ${{ needs.find-snyk-vulns.outputs.vulns }}      
    steps:
      - id: set-trail-names
        run: |
          trail_names=$(echo "${VULNS}" | \
            jq --compact-output --arg repo '${{inputs.repo_name}}' \
            '[.[] | "\($repo)-\(.snyk_severity)-\(.snyk_full_id)"]')
          echo "trail_names=${trail_names}" >> ${GITHUB_OUTPUT}
