name: Live Snyk Test aws-beta

on:
  workflow_dispatch:
  push:
  #schedule: # At 06:00 every day
  #  - cron: '0 6 * * *'

jobs:
  scan-aws-beta:
    uses: ./.github/workflows/env_snyk_test.yml
    with:
      kosli_env: aws-beta
      kosli_flow: snyk-vulns-aws-beta
    secrets:
      snyk_token: ${{secrets.SNYK_TOKEN}}
      kosli_api_token: ${{secrets.KOSLI_API_TOKEN}}
