name: Live Snyk Test aws-prod

on:
  workflow_dispatch:
  schedule: # At 01:39 UTC every day; cron delays of a few hours are not unusual in high load
    - cron: '39 1 * * *'
  push:
    branches: [main]
    paths:
      - snyk-vuln-compliance.rego
      - rego.params.aws-prod.json

env:
  KOSLI_DEBUG:   ${{vars.KOSLI_DEBUG}}   # false
  KOSLI_DRY_RUN: ${{vars.KOSLI_DRY_RUN}} # false
  KOSLI_HOST:    ${{vars.KOSLI_HOST}}    # https://app.kosli.com
  KOSLI_ORG:     ${{vars.KOSLI_ORG}}     # cyber-dojo

  KOSLI_ENV:  aws-prod
  KOSLI_FLOW: snyk-aws-prod-per-artifact

jobs:
  setup-flow:
    runs-on: ubuntu-latest
    outputs:
      kosli_env: ${{steps.set-outputs.outputs.kosli_env}}
      kosli_flow: ${{steps.set-outputs.outputs.kosli_flow}}
    env:
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
    steps:
      - uses: cyber-dojo/harden-runner@main
      - uses: cyber-dojo/setup-kosli-cli@main

      - name: Create Flow
        run:
          kosli create flow ${KOSLI_FLOW}
            --description "Snyk vulns in ${KOSLI_ENV} artifacts"
            --use-empty-template

      - run: |
          path=$(echo "${{github.workflow_ref}}" | sed 's|.*/.github|/.github|' | sed 's|@.*||')
          URL="${{github.server_url}}/${{github.repository}}/blob/${{github.ref_name}}${path}"
          echo "WORKFLOW_URL=${URL}" >> "$GITHUB_ENV"

      - name: Tag the Flow
        run:
          kosli tag flow ${KOSLI_FLOW}
            --set env=${KOSLI_ENV}
            --set kind=run
            --set ci=github
            --set workflow_url="${WORKFLOW_URL}"

      - name: Set outputs
        id: set-outputs
        run: |
          echo "kosli_env=${KOSLI_ENV}" >> $GITHUB_OUTPUT
          echo "kosli_flow=${KOSLI_FLOW}" >> $GITHUB_OUTPUT


  scan-aws-prod:
    needs: [setup-flow]
    uses: ./.github/workflows/env_snyk_test.yml
    with:
      kosli_env: ${{needs.setup-flow.outputs.kosli_env}}
      kosli_flow: ${{needs.setup-flow.outputs.kosli_flow}}
    secrets:
      snyk_token:      ${{secrets.SNYK_TOKEN}}
      kosli_api_token: ${{secrets.KOSLI_API_TOKEN}}


  notify-next-expiry:
    needs: [setup-flow, scan-aws-prod]
    uses: ./.github/workflows/check-expiry-and-notify.yml
    with:
      kosli_env: ${{needs.setup-flow.outputs.kosli_env}}
    secrets:
      SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}


  notify-on-failure:
    needs: [setup-flow, scan-aws-prod, notify-next-expiry]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Send Slack failure notification
        uses: ./.github/actions/send-slack-message
        with:
          slack_url: ${{secrets.SLACK_WEBHOOK_URL}}
          message: "Snyk scan FAILED for ${{env.KOSLI_ENV}}.\nSee ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
