name: Create Custom Attestation Type

on:
  workflow_call:
    outputs:
      name:
        description: "Name of the custom attestation type created"
        value: ${{jobs.create-snyk-cat.outputs.name}}
    secrets:
      kosli_api_token:
        required: true

env:
  KOSLI_DEBUG:   ${{vars.KOSLI_DEBUG}}   # true/false
  KOSLI_DRY_RUN: ${{vars.KOSLI_DRY_RUN}} # true/false
  KOSLI_HOST:    ${{vars.KOSLI_HOST}}    # https://app.kosli.com
  KOSLI_ORG:     ${{vars.KOSLI_ORG}}     # cyber-dojo

jobs:

  create-snyk-cat:
    runs-on: ubuntu-latest
    outputs:
      name: ${{steps.create.outputs.name}}
    steps:
      - uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@v6
        with:
          repository: cyber-dojo/snyk-scanning
          ref: main
          fetch-depth: 1

      - name: Setup Kosli CLI
        uses: kosli-dev/setup-cli-action@v3
        with:
          version: ${{vars.KOSLI_CLI_VERSION}}

      - name: Create custom-attestation-type
        id: create
        env:
          KOSLI_API_TOKEN: ${{secrets.kosli_api_token}}
        run: |
          name=single-snyk-vuln
          kosli create attestation-type \
            ${name} \
            --schema single-snyk-vuln.schema.json \
            --jq 'true'
          echo "name=${name}" >> ${GITHUB_OUTPUT}
