name: Artifacts in aws-beta and aws-prod environments

on:
  push:
  schedule: 
    - cron: '0 6 * * *' # At 06:00 every day
  # workflow_dispatch: # Allow manual triggering

env:
  KOSLI_DEBUG:   ${{ vars.KOSLI_DEBUG }}   # true/false
  KOSLI_DRY_RUN: ${{ vars.KOSLI_DRY_RUN }} # true/false
  KOSLI_HOST:    ${{ vars.KOSLI_HOST }}    # https://app.kosli.com
  KOSLI_ORG:     ${{ vars.KOSLI_ORG }}     # cyber-dojo

jobs:
  setup:
    needs: []
    runs-on: ubuntu-latest
    outputs:
      kosli_trail: ${{ steps.set-kosli-trail.outputs.kosli_trail }}
    steps:
      - name: Setup Kosli CLI
        uses: kosli-dev/setup-cli-action@v3
        with:
          version: ${{ vars.KOSLI_CLI_VERSION }}

      - name: Create Kosli Flows with descriptions
        env:
          KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
        run: |
          kosli create flow aws-beta-all-snyk-vulns \
            --use-empty-template \
            --description="All snyk vulns currently in aws-beta"
          kosli create flow aws-prod-all-snyk-vulns \
            --use-empty-template \
            --description="All snyk vulns currently in aws-prod"
          kosli create flow aws-beta-new-snyk-vulns \
            --use-empty-template \
            --description="New snyk vulns, since deployment, in aws-beta"
          kosli create flow aws-prod-new-snyk-vulns \
            --use-empty-template \
            --description="New snyk vulns, since deployment, in aws-beta"

      - name: Create Kosli Tags
        env:
          KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
        run: |
          kosli tag flow aws-beta-all-snyk-vulns \
            --set kind=run \
            --set ci=github \
            --set repo_url=https://github.com/${{ github.repository }}
          kosli tag flow aws-prod-all-snyk-vulns \
            --set kind=run \
            --set ci=github \
            --set repo_url=https://github.com/${{ github.repository }}
          kosli tag flow aws-beta-new-snyk-vulns \
            --set kind=run \
            --set ci=github \
            --set repo_url=https://github.com/${{ github.repository }}
          kosli tag flow aws-prod-new-snyk-vulns \
            --set kind=run \
            --set ci=github \
            --set repo_url=https://github.com/${{ github.repository }}

      - name: Set kosli-trail output
        id: set-kosli-trail
        run:
          echo "kosli_trail=$(date +%Y-%m-%dT%H.%M.%S)" >> ${GITHUB_OUTPUT}


  aws-beta-new-env-snyk:
    needs: [setup]
    uses: ./.github/workflows/env_new_snyk.yml
    with:
      kosli_env:                  aws-beta
      kosli_flow_name_all_vulns:  aws-beta-all-snyk-vulns
      kosli_trail_name_all_vulns: ${{ needs.setup.outputs.kosli_trail }}
      kosli_flow_name_new_vulns:  aws-beta-new-snyk-vulns
    secrets:
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
      SNYK_TOKEN:      ${{ secrets.SNYK_TOKEN }}

  aws-prod-new-env-snyk:
    needs: [setup]
    uses: ./.github/workflows/env_new_snyk.yml
    with:
      kosli_env:                  aws-prod
      kosli_flow_name_all_vulns:  aws-prod-all-snyk-vulns
      kosli_trail_name_all_vulns: ${{ needs.setup.outputs.kosli_trail }}
      kosli_flow_name_new_vulns:  aws-prod-new-snyk-vulns
    secrets:
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
      SNYK_TOKEN:      ${{ secrets.SNYK_TOKEN }}
