name: Live Snyk Test of aws-beta and aws-prod

on:
  #workflow_dispatch:
  push:
  #schedule: # At 06:00 every day
  #  - cron: '0 6 * * *'

jobs:
  setup:
    needs: []
    runs-on: ubuntu-latest
    outputs:
      kosli_trail: ${{ steps.set-kosli-trail.outputs.kosli_trail }}
    steps:
      - name: Set kosli-trail output
        id: set-kosli-trail
        run:
          echo "kosli_trail=$(date +%Y-%m-%dT%H.%M.%S)" >> ${GITHUB_OUTPUT}

  aws-beta-new-env-snyk:
    needs: [setup]
    uses: ./.github/workflows/env_new_snyk.yml
    with:
      kosli_env: aws-beta
      kosli_flow_name_all_vulns: aws-beta-all-snyk-vulns
      kosli_trail_name_all_vulns: ${{ needs.setup.outputs.kosli_trail }}
      kosli_flow_name_new_vulns: aws-beta-new-snyk-vulns
    secrets:
      snyk_token:      ${{ secrets.snyk_token }}
      kosli_api_token: ${{ secrets.kosli_api_token }}

  aws-prod-new-env-snyk:
    needs: [setup]
    uses: ./.github/workflows/env_new_snyk.yml
    with:
      kosli_env: aws-prod
      kosli_flow_name_all_vulns: aws-prod-all-snyk-vulns
      kosli_trail_name_all_vulns: ${{ needs.setup.outputs.kosli_trail }}
      kosli_flow_name_new_vulns: aws-prod-new-snyk-vulns
    secrets:
      snyk_token:      ${{ secrets.snyk_token }}
      kosli_api_token: ${{ secrets.kosli_api_token }}
