name: Live Snyk Test

on:
  #workflow_dispatch:
  push:
  #schedule: # At 08:00 every day
  #  - cron: '0 8 * * *'

# env:
#   KOSLI_DEBUG:   ${{ vars.KOSLI_DEBUG }}   # true/false
#   KOSLI_DRY_RUN: ${{ vars.KOSLI_DRY_RUN }} # true/false
#   KOSLI_HOST:    ${{ vars.KOSLI_HOST }}    # https://app.kosli.com
#   KOSLI_ORG:     ${{ vars.KOSLI_ORG }}     # cyber-dojo

jobs:
  aws-beta-new-env-snyk:
    needs: []
    uses: ./.github/workflows/new_env_snyk.yml
