# Debug workflow to work on 2nd half of artifact_snyk_test.yml 
# when there are no vulns 

name: Artifact Snyk Test on saver

on:
  push:

jobs:
  call-with-saver:
    uses: ./.github/workflows/artifact_snyk_test.yml
    with:
      artifact_name: 244531986313.dkr.ecr.eu-central-1.amazonaws.com/saver:5d42c57@sha256:b2e822b4829bc7447f2622eb3621a1b10452fa503a98b7aa15ba714acef2abd9
      raw_snyk_policy_url: https://raw.githubusercontent.com/cyber-dojo/saver/5d42c570fa37dc38b5f5652b1e38230efd18f4b6/.snyk
      repo_name: saver
      kosli_flow: saver-ci
      kosli_trail: ${{ github.sha }}
      kosli_fingerprint: b2e822b4829bc7447f2622eb3621a1b10452fa503a98b7aa15ba714acef2abd9
      kosli_slot: saver.new-snyk-container-scan
    secrets:
      snyk_token:      ${{secrets.SNYK_TOKEN}}
      kosli_api_token: ${{secrets.KOSLI_API_TOKEN}}

  print-vulns:
    needs: [call-with-saver]
    runs-on: ubuntu-latest
    env:
      VULNS_JSON: ${{needs.call-with-saver.outputs.vulns_json}}
    steps:
      - name: Print json
        run:
          jq . <<< "${VULNS_JSON}"
