name: Snyk Test a Live Artifact

on:
  workflow_call:
    secrets:
      snyk_token:
        required: true
      kosli_api_token:
        required: true

    inputs:
      artifact_name:
        description: "Artifact name"
        required: true
        type: string
      artifact_fingerprint:
        description: "Artifact fingerprint/digest (64 chars)"
        required: true
        type: string
      repo_name:
        description: "Artifact repo"
        required: true
        type: string
      git_commit:
        description: "Artifact commit (40 chars)"
        required: true
        type: string
      commit_url:
        description: "Artifact commit URL"
        required: true
        type: string
      kosli_env:
        description: "Name of Kosli environment the artifact is running in"
        required: true
        type: string
      kosli_trail:
        description: "The name of the new Trail to create holding attestations for all snyk vulns in the given Env"
        required: true
        type: string

env:
  KOSLI_DEBUG:   ${{ vars.KOSLI_DEBUG }}   # true/false
  KOSLI_DRY_RUN: ${{ vars.KOSLI_DRY_RUN }} # true/false
  KOSLI_HOST:    ${{ vars.KOSLI_HOST }}    # https://app.kosli.com
  KOSLI_ORG:     ${{ vars.KOSLI_ORG }}     # cyber-dojo


jobs:
  find-all-snyk-vulns:
    runs-on: ubuntu-latest
    outputs:
      vulns:   ${{ steps.set-vulns.outputs.vulns }}
      version: ${{ steps.set-version.outputs.version }}
    permissions:
      id-token: write
      contents: write
    env:
      SNYK_SARIF_FILENAME: snyk.container.test.json
      SNYK_POLICY_FILENAME: .snyk
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Load docker image from registry
        uses: cyber-dojo/load-image-from-registry@main
        with:
          image_name: "${{ inputs.artifact_name }}"
          aws_rolename: "gh_actions_live_snyk_scans"

      - name: Setup Snyk
        uses: snyk/actions/setup@master
        with:
          snyk-version: v1.1300.2

      - name: Set empty .snyk policy file
        run:
          echo '' > "${SNYK_POLICY_FILENAME}"

      - name: Run Snyk container test
        env:
          SNYK_TOKEN: ${{ secrets.snyk_token }}
        run:
          snyk container test "${{ inputs.artifact_name }}"
            --policy-path="${SNYK_POLICY_FILENAME}"
            --sarif
            --sarif-file-output="${SNYK_SARIF_FILENAME}" || true

      - name: Fail if the sarif file is not created
        run: |
          if ! test -f "${SNYK_SARIF_FILENAME}" ; then
            echo "ERROR: ${SNYK_SARIF_FILENAME} was not created"
            exit 43
          fi

      - name: Get vulns from sarif file
        id: set-vulns
        env:
          JSON_FILENAME: vulns.json
        run: |
          ./bin/get_sarif_vulns.py ${SNYK_SARIF_FILENAME} > ${JSON_FILENAME}
          vulns="$(jq --compact-output . ${JSON_FILENAME})"
          jq . <<< "${vulns}"
          echo "vulns=${vulns}" >> ${GITHUB_OUTPUT}

      # - name: Fake combining snyk vulns from sarif file with ignore-expiries in Snyk policy file
      #   id: set-vulns
      #   env:
      #     JSON_FILENAME: vulns.json
      #   run: |
      #     cp fake-data/snyk-${{ inputs.repo_name }}.json ${JSON_FILENAME}
      #     vulns="$(jq --compact-output . ${JSON_FILENAME})"
      #     jq . <<< "${vulns}"
      #     echo "vulns=${vulns}" >> ${GITHUB_OUTPUT}

      - name: Output snyk version
        id: set-version
        run:
          echo "version=$(snyk --version)" >> ${GITHUB_OUTPUT}


  no-snyk-vulns:
    needs: find-all-snyk-vulns
    if: ${{ needs.find-all-snyk-vulns.outputs.vulns == '[]' }}
    runs-on: ubuntu-latest
    env:
      ATTESTATION_DATA_FILENAME: no-snyk-vuln.json
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup Kosli CLI
        uses: kosli-dev/setup-cli-action@v2
        with:
          version: ${{ vars.KOSLI_CLI_VERSION }}
      
      - name: Create file containing custom attestation data
        run:
          jq
            --arg repo_name            "${{ inputs.repo_name }}"
            --arg git_commit           "${{ inputs.git_commit }}"
            --arg commit_url           "${{ inputs.commit_url }}"
            --arg artifact_name        "${{ inputs.artifact_name }}"
            --arg artifact_fingerprint "${{ inputs.artifact_fingerprint }}"
            --arg snyk_version         "${{ needs.find-all-snyk-vulns.outputs.version }}"
            --arg snyk_full_id          ''
            --arg snyk_short_id         ''
            --arg snyk_severity         ''
            --arg snyk_vuln_url         ''
            '$ARGS.named' <<< '{}' 
            > ${ATTESTATION_DATA_FILENAME}

      - name: Attest no-vulns to Kosli
        env:
          KOSLI_API_TOKEN: ${{ secrets.kosli_api_token }}
          KOSLI_FLOW:      ${{ inputs.kosli_env }}-all-snyk-vulns-TEST
          KOSLI_TRAIL:     ${{ inputs.kosli_trail }}
        run:
          kosli attest custom
            --type single-snyk-vuln
            --attestation-data ${ATTESTATION_DATA_FILENAME}
            --name ${{ inputs.repo_name }}-none


  some-snyk-vulns:
    needs: find-all-snyk-vulns
    if: ${{ needs.find-all-snyk-vulns.outputs.vulns != '[]' }}
    runs-on: ubuntu-latest
    env:
      ATTESTATION_DATA_FILENAME: single-snyk-vuln.json
    strategy:
      matrix:
        include: ${{ fromJSON(needs.find-all-snyk-vulns.outputs.vulns) }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup Kosli CLI
        uses: kosli-dev/setup-cli-action@v2
        with:
          version: ${{vars.KOSLI_CLI_VERSION}}

      - name: Create file containing custom attestation data
        run:
          jq
            --arg repo_name            "${{ inputs.repo_name }}"
            --arg git_commit           "${{ inputs.git_commit }}"
            --arg commit_url           "${{ inputs.commit_url }}"
            --arg artifact_name        "${{ inputs.artifact_name }}"
            --arg artifact_fingerprint "${{ inputs.artifact_fingerprint }}"
            --arg snyk_version         "${{ needs.find-all-snyk-vulns.outputs.version }}"
            --arg snyk_full_id         "${{ matrix.snyk_full_id }}"
            --arg snyk_short_id        "${{ matrix.snyk_short_id }}"
            --arg snyk_severity        "${{ matrix.snyk_severity }}"
            --arg snyk_vuln_url        "${{ matrix.snyk_vuln_url }}"
            '$ARGS.named' <<< '{}' 
            > ${ATTESTATION_DATA_FILENAME}

      - name: Attest single-snyk-vuln to Kosli
        env:
          KOSLI_API_TOKEN: ${{ secrets.kosli_api_token }}
          KOSLI_FLOW:      ${{ inputs.kosli_env }}-all-snyk-vulns-TEST
          KOSLI_TRAIL:     ${{ inputs.kosli_trail }}
        run:
          kosli attest custom
            --type single-snyk-vuln
            --annotate snyk_URL=${{ matrix.snyk_vuln_url }}
            --attestation-data ${ATTESTATION_DATA_FILENAME}
            --name ${{ inputs.repo_name }}-${{ matrix.snyk_severity }}-${{ matrix.snyk_short_id }}
