name: Live Snyk test of all artifacts deployed to an environment

on:
  workflow_call:
    secrets:
      snyk_token:
        required: true
      kosli_api_token:
        required: true

    inputs:
      kosli_env:
        description: "Name of Kosli environment to snyk test"
        required: true
        type: string
      kosli_flow_name_all_vulns:
        description: "Name of Kosli Flow to attest all vulns in Environment"
        required: true
        type: string      
      kosli_trail_name_all_vulns:
        description: "The name of the Kosli Trail to create holding the most recent attestations for all snyk vulns in the given Env"
        required: true
        type: string

env:
  KOSLI_DEBUG:   ${{ vars.KOSLI_DEBUG }}   # true/false
  KOSLI_DRY_RUN: ${{ vars.KOSLI_DRY_RUN }} # true/false
  KOSLI_HOST:    ${{ vars.KOSLI_HOST }}    # https://app.kosli.com
  KOSLI_ORG:     ${{ vars.KOSLI_ORG }}     # cyber-dojo

jobs:

  find-env-artifacts:
    runs-on: ubuntu-latest
    outputs:
      artifacts: ${{ steps.set-artifacts.outputs.artifacts }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup Kosli CLI
        uses: kosli-dev/setup-cli-action@v2
        with:
          version: ${{ vars.KOSLI_CLI_VERSION }}

      - name: Generate JSON for each Artifact in kosli_env for following job's strategy:matrix:include
        id: set-artifacts
        env:
          KOSLI_API_TOKEN: ${{ secrets.kosli_api_token }}
        run: |
          ./bin/kosli_get_snapshot_json.sh > debug.json
          jq . debug.json
          cat debug.json | ./bin/artifacts.py
          artifacts="$(make artifacts | jq --raw-output --compact-output .)"
          echo "artifacts=${artifacts}" >> ${GITHUB_OUTPUT}

      # Fake getting snapshot from kosli_env
      # - id: set-artifacts
      #   run: |
      #     artifacts="$(jq --compact-output . fake-data/artifacts-${{ inputs.kosli_env }}.json)"
      #     echo "artifacts=${artifacts}" >> ${GITHUB_OUTPUT}


  env-artifact-snyk:
    needs: find-env-artifacts
    strategy:
      matrix:
        include: ${{ fromJSON(needs.find-env-artifacts.outputs.artifacts) }}
    uses: ./.github/workflows/snyk_artifact_test.yml
    with:
      artifact_name:        ${{ matrix.artifact_name }}
      artifact_fingerprint: ${{ matrix.artifact_fingerprint }}
      repo_name:            ${{ matrix.repo_name }}
      git_commit:           ${{ matrix.git_commit }}
      commit_url:           ${{ matrix.commit_url }}
      kosli_flow_name_all_vulns:  ${{ inputs.kosli_flow_name_all_vulns }}
      kosli_trail_name_all_vulns: ${{ inputs.kosli_trail_name_all_vulns }}
    secrets:
      snyk_token:      ${{ secrets.snyk_token }}
      kosli_api_token: ${{ secrets.kosli_api_token }}

